### ISSUE TITLE
Customize

### ISSUE THREAD

**Issue by xarlotie** [mattfxyz/MFAButton#2]
Hi,

How can we make the parent view still accessible even when the option list is visible?

I'm trying to change the size of the backgroundView but it doesn't work. Can you share a solution? Thanks!

**Comment by mattfxyz** [comment]
The parent view can be accessed if you push touches from the child (the overlay) through to the parent. 

It's done like this 

```
// Passes a click through the view.
-(id)hitTest:(CGPoint)point withEvent:(UIEvent *)event {
    id hitView = [super hitTest:point withEvent:event];
    if (hitView == self) // checks to see which view the touch was on
        return nil;
    else
        return hitView;
}
```

**Comment by xarlotie** [comment]
I dont need to do any special or additional event. I have a scrollview below the MFAButton. When the button options are visible, it prevents scrolling the scrollview under it. I just want that scrollview to still be scrollable even when the button options are visible.

**Comment by mattfxyz** [comment]
you'll have to do some fiddling in the method above. This is just me tampering
